version: '2'

services:
  lb:
    networks:
      - ottoinfo-lb-net
    container_name: ottoinfo_lb_instance
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
    build:
      context: .
    image: ottoinfo/lb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

networks:
  ottoinfo-lb-net:
    external: true
