version: '3.4'

services:
  mysql:
    networks:
      - mysql-net
      - node-net
    container_name: mysql_instance
    image: mysql:5.7.17
    user: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - $MYSQL_STORAGE_DIR:/var/lib/mysql

networks:
  node-net:
    external: true
  mysql-net:
    external: true
